/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aufgabe1;
import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
/**
 *
 * @author Volkan
 */
public class View extends javax.swing.JFrame {

    DefaultListModel BilderModel = null;
    DefaultListModel PersonenModel = null;
    public View() {
        initComponents();
        ButtonGruppe.setSelected(jRadioButton_Einzelauswahl.getModel(), true);
        BildModel();
        PersonenModel();
        BildListener();
        PersonenListener();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonGruppe = new javax.swing.ButtonGroup();
        jScrollPane_BilderListe = new javax.swing.JScrollPane();
        jList_BilderListe = new javax.swing.JList<>();
        jRadioButton_Einzelauswahl = new javax.swing.JRadioButton();
        jRadioButton_Bereichsauswahl = new javax.swing.JRadioButton();
        jRadioButton_Mehrfachauswahl = new javax.swing.JRadioButton();
        jScrollPane_Personennamen = new javax.swing.JScrollPane();
        jList_Personennamen = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jList_BilderListe.setModel(jList_BilderListe.getModel());
        jList_BilderListe.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane_BilderListe.setViewportView(jList_BilderListe);

        ButtonGruppe.add(jRadioButton_Einzelauswahl);
        jRadioButton_Einzelauswahl.setText("Einzelauswahl");
        jRadioButton_Einzelauswahl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_EinzelauswahlActionPerformed(evt);
            }
        });

        ButtonGruppe.add(jRadioButton_Bereichsauswahl);
        jRadioButton_Bereichsauswahl.setText("Bereichsauswahl");
        jRadioButton_Bereichsauswahl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_BereichsauswahlActionPerformed(evt);
            }
        });

        ButtonGruppe.add(jRadioButton_Mehrfachauswahl);
        jRadioButton_Mehrfachauswahl.setText("Mehrfachauswahl");
        jRadioButton_Mehrfachauswahl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_MehrfachauswahlActionPerformed(evt);
            }
        });

        jList_Personennamen.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jList_Personennamen.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane_Personennamen.setViewportView(jList_Personennamen);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jScrollPane_BilderListe, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(164, 164, 164)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jRadioButton_Mehrfachauswahl)
                        .addComponent(jRadioButton_Bereichsauswahl, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jRadioButton_Einzelauswahl, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jScrollPane_Personennamen, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane_BilderListe, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButton_Einzelauswahl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton_Bereichsauswahl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton_Mehrfachauswahl)
                        .addGap(65, 65, 65)
                        .addComponent(jScrollPane_Personennamen, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jRadioButton_MehrfachauswahlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_MehrfachauswahlActionPerformed
        jList_BilderListe.setSelectedIndex(0);
        jList_BilderListe.setSelectionMode(2);
    }//GEN-LAST:event_jRadioButton_MehrfachauswahlActionPerformed

    private void jRadioButton_BereichsauswahlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_BereichsauswahlActionPerformed
        jList_BilderListe.setSelectedIndex(0);
        jList_BilderListe.setSelectionMode(1);
    }//GEN-LAST:event_jRadioButton_BereichsauswahlActionPerformed

    private void jRadioButton_EinzelauswahlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_EinzelauswahlActionPerformed
        jList_BilderListe.setSelectedIndex(0);
        jList_BilderListe.setSelectionMode(0);
    }//GEN-LAST:event_jRadioButton_EinzelauswahlActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup ButtonGruppe;
    private javax.swing.JList<String> jList_BilderListe;
    private javax.swing.JList<String> jList_Personennamen;
    private javax.swing.JRadioButton jRadioButton_Bereichsauswahl;
    private javax.swing.JRadioButton jRadioButton_Einzelauswahl;
    private javax.swing.JRadioButton jRadioButton_Mehrfachauswahl;
    private javax.swing.JScrollPane jScrollPane_BilderListe;
    private javax.swing.JScrollPane jScrollPane_Personennamen;
    // End of variables declaration//GEN-END:variables
private void BildModel() {
        BilderModel = new DefaultListModel();
        for (int i = 0; i < 17; i++) {
            BilderModel.addElement(
                    new ImageIcon(getClass().getResource("Pictures/" + (i + 1) + ".jpg")));
        }
        jList_BilderListe.setModel(BilderModel);
    }

    private void PersonenModel()  {
         PersonenModel = new DefaultListModel();
         
         try {
            FileInputStream fstream = new FileInputStream("src/aufgabe1/Personennamen.txt");
            BufferedReader br = new BufferedReader(new InputStreamReader(fstream));
    for(String line; (line = br.readLine()) != null; ) {
        PersonenModel.addElement(line);
    }
    // line is not visible here.
}       catch (IOException ex) {
            System.out.println(ex);
        }
    jList_Personennamen.setModel(PersonenModel);
}
    
    private void PersonenModelAuswahl(int value)  {
         PersonenModel = new DefaultListModel();
         int a = 0;
         try {
            FileInputStream fstream = new FileInputStream("src/aufgabe1/Personennamen.txt");
            BufferedReader br = new BufferedReader(new InputStreamReader(fstream));
    for(String line; (line = br.readLine()) != null; ) {
        if(a==value) PersonenModel.addElement(line);
        a++;
    }
    // line is not visible here.
}       catch (IOException ex) {
            System.out.println(ex);
        }
    jList_Personennamen.setModel(PersonenModel);
}
    
    private void BildListener(){
        ListSelectionListener BildListener = new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                PersonenModelAuswahl(jList_BilderListe.getSelectedIndex());
            }
        };
        jList_BilderListe.addListSelectionListener(BildListener);
    }
    
    private void PersonenListener(){
        ListSelectionListener PersonenListener = new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                 
            }
        };
        jList_Personennamen.addListSelectionListener(PersonenListener);
    }
}
