/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aufgabe2;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author Volkan
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
        DocumentListener();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneLinks = new javax.swing.JScrollPane();
        TextAreaLinks = new javax.swing.JTextArea();
        jScrollPaneRechts = new javax.swing.JScrollPane();
        TextAreaRechts = new javax.swing.JTextArea();
        ToolBar = new javax.swing.JToolBar();
        jToolKopieren = new javax.swing.JButton();
        jToolAusschneiden = new javax.swing.JButton();
        jToolEinfuegen = new javax.swing.JButton();
        jToolGrossbuchstaben = new javax.swing.JButton();
        jToolKleinbuchstaben = new javax.swing.JButton();
        jButtonGrossbuchstaben = new javax.swing.JButton();
        jButtonKleinbuchstaben = new javax.swing.JButton();
        MenueBar = new javax.swing.JMenuBar();
        MenueDatei = new javax.swing.JMenu();
        jMenuItemBeenden = new javax.swing.JMenuItem();
        MenueBearbeiten = new javax.swing.JMenu();
        jMenuItemAusschneiden = new javax.swing.JMenuItem();
        jMenuItemKopieren = new javax.swing.JMenuItem();
        jMenuItemEinfuegen = new javax.swing.JMenuItem();
        jSeparatorBearbeiten = new javax.swing.JPopupMenu.Separator();
        jMenuItemGrossbuchstaben = new javax.swing.JMenuItem();
        jMenuItemKleinbuchstaben = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aufgabe 2");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        TextAreaLinks.setColumns(20);
        TextAreaLinks.setRows(5);
        jScrollPaneLinks.setViewportView(TextAreaLinks);

        TextAreaRechts.setColumns(20);
        TextAreaRechts.setRows(5);
        jScrollPaneRechts.setViewportView(TextAreaRechts);

        ToolBar.setFloatable(false);
        ToolBar.setRollover(true);

        jToolKopieren.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aufgabe2/Symbole/kopieren.gif"))); // NOI18N
        jToolKopieren.setDisabledIcon(null);
        jToolKopieren.setEnabled(false);
        jToolKopieren.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToolKopieren.setMargin(new java.awt.Insets(0, 20, 0, 20));
        jToolKopieren.setMaximumSize(new java.awt.Dimension(40, 40));
        jToolKopieren.setMinimumSize(new java.awt.Dimension(50, 30));
        jToolKopieren.setPreferredSize(new java.awt.Dimension(50, 30));
        jToolKopieren.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolKopieren.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToolKopierenActionPerformed(evt);
            }
        });
        ToolBar.add(jToolKopieren);

        jToolAusschneiden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aufgabe2/Symbole/ausschneiden.gif"))); // NOI18N
        jToolAusschneiden.setEnabled(false);
        jToolAusschneiden.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToolAusschneiden.setMargin(new java.awt.Insets(0, 20, 0, 20));
        jToolAusschneiden.setMaximumSize(new java.awt.Dimension(40, 40));
        jToolAusschneiden.setMinimumSize(new java.awt.Dimension(50, 30));
        jToolAusschneiden.setPreferredSize(new java.awt.Dimension(50, 30));
        jToolAusschneiden.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolAusschneiden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToolAusschneidenActionPerformed(evt);
            }
        });
        ToolBar.add(jToolAusschneiden);

        jToolEinfuegen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aufgabe2/Symbole/einfuegen.gif"))); // NOI18N
        jToolEinfuegen.setDisabledIcon(null);
        jToolEinfuegen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToolEinfuegen.setMargin(new java.awt.Insets(0, 20, 0, 20));
        jToolEinfuegen.setMaximumSize(new java.awt.Dimension(40, 40));
        jToolEinfuegen.setMinimumSize(new java.awt.Dimension(50, 30));
        jToolEinfuegen.setPreferredSize(new java.awt.Dimension(50, 30));
        jToolEinfuegen.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolEinfuegen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToolEinfuegenActionPerformed(evt);
            }
        });
        ToolBar.add(jToolEinfuegen);

        jToolGrossbuchstaben.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aufgabe2/Symbole/gross.gif"))); // NOI18N
        jToolGrossbuchstaben.setToolTipText("Wandelt den ausgewählten Text in Großbuchstaben um.");
        jToolGrossbuchstaben.setDisabledIcon(null);
        jToolGrossbuchstaben.setEnabled(false);
        jToolGrossbuchstaben.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToolGrossbuchstaben.setMargin(new java.awt.Insets(0, 20, 0, 20));
        jToolGrossbuchstaben.setMaximumSize(new java.awt.Dimension(40, 40));
        jToolGrossbuchstaben.setMinimumSize(new java.awt.Dimension(50, 30));
        jToolGrossbuchstaben.setPreferredSize(new java.awt.Dimension(50, 30));
        jToolGrossbuchstaben.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolGrossbuchstaben.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToolGrossbuchstabenActionPerformed(evt);
            }
        });
        ToolBar.add(jToolGrossbuchstaben);

        jToolKleinbuchstaben.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aufgabe2/Symbole/klein.gif"))); // NOI18N
        jToolKleinbuchstaben.setToolTipText("Wandelt den ausgewählten Text in Kleinbuchstaben um.");
        jToolKleinbuchstaben.setDisabledIcon(null);
        jToolKleinbuchstaben.setEnabled(false);
        jToolKleinbuchstaben.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToolKleinbuchstaben.setMargin(new java.awt.Insets(0, 20, 0, 20));
        jToolKleinbuchstaben.setMaximumSize(new java.awt.Dimension(40, 40));
        jToolKleinbuchstaben.setMinimumSize(new java.awt.Dimension(50, 30));
        jToolKleinbuchstaben.setPreferredSize(new java.awt.Dimension(50, 30));
        jToolKleinbuchstaben.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolKleinbuchstaben.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToolKleinbuchstabenActionPerformed(evt);
            }
        });
        ToolBar.add(jToolKleinbuchstaben);

        jButtonGrossbuchstaben.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aufgabe2/Symbole/gross.gif"))); // NOI18N
        jButtonGrossbuchstaben.setText("Großbuchstaben");
        jButtonGrossbuchstaben.setToolTipText("Wandelt den ausgewählten Text in Großbuchstaben um.");
        jButtonGrossbuchstaben.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGrossbuchstabenActionPerformed(evt);
            }
        });

        jButtonKleinbuchstaben.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aufgabe2/Symbole/klein.gif"))); // NOI18N
        jButtonKleinbuchstaben.setText("Kleinbuchstaben");
        jButtonKleinbuchstaben.setToolTipText("Wandelt den ausgewählten Text in Kleinbuchstaben um.");
        jButtonKleinbuchstaben.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKleinbuchstabenActionPerformed(evt);
            }
        });

        MenueDatei.setText("Datei");

        jMenuItemBeenden.setText("Beenden");
        jMenuItemBeenden.setToolTipText("Beendet die Applikation");
        jMenuItemBeenden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBeendenActionPerformed(evt);
            }
        });
        MenueDatei.add(jMenuItemBeenden);

        MenueBar.add(MenueDatei);

        MenueBearbeiten.setText("Bearbeiten");

        jMenuItemAusschneiden.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemAusschneiden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aufgabe2/Symbole/ausschneiden.gif"))); // NOI18N
        jMenuItemAusschneiden.setText("Ausschneiden");
        jMenuItemAusschneiden.setToolTipText("Kopiert den ausgewählen Text in die Zwischenablage und entfernt den selektierten Text.");
        jMenuItemAusschneiden.setEnabled(false);
        jMenuItemAusschneiden.setFocusable(true);
        jMenuItemAusschneiden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAusschneidenActionPerformed(evt);
            }
        });
        MenueBearbeiten.add(jMenuItemAusschneiden);

        jMenuItemKopieren.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemKopieren.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aufgabe2/Symbole/kopieren.gif"))); // NOI18N
        jMenuItemKopieren.setText("Kopieren");
        jMenuItemKopieren.setToolTipText("Kopiert den ausgewählen Text in die Zwischenablage.");
        jMenuItemKopieren.setEnabled(false);
        jMenuItemKopieren.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemKopierenActionPerformed(evt);
            }
        });
        MenueBearbeiten.add(jMenuItemKopieren);

        jMenuItemEinfuegen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemEinfuegen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aufgabe2/Symbole/einfuegen.gif"))); // NOI18N
        jMenuItemEinfuegen.setText("Einfügen");
        jMenuItemEinfuegen.setToolTipText("FÜgt den Text aus der Zwischenablage ein.");
        jMenuItemEinfuegen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEinfuegenActionPerformed(evt);
            }
        });
        MenueBearbeiten.add(jMenuItemEinfuegen);
        MenueBearbeiten.add(jSeparatorBearbeiten);

        jMenuItemGrossbuchstaben.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemGrossbuchstaben.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aufgabe2/Symbole/gross.gif"))); // NOI18N
        jMenuItemGrossbuchstaben.setText("Großbuchstaben");
        jMenuItemGrossbuchstaben.setToolTipText("Wandelt den ausgewählten Text in Großbuchstaben um.");
        jMenuItemGrossbuchstaben.setEnabled(false);
        jMenuItemGrossbuchstaben.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGrossbuchstabenActionPerformed(evt);
            }
        });
        MenueBearbeiten.add(jMenuItemGrossbuchstaben);

        jMenuItemKleinbuchstaben.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemKleinbuchstaben.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aufgabe2/Symbole/klein.gif"))); // NOI18N
        jMenuItemKleinbuchstaben.setText("Kleinbuchstaben");
        jMenuItemKleinbuchstaben.setToolTipText("Wandelt den ausgewählten Text in Kleinbuchstaben um.");
        jMenuItemKleinbuchstaben.setEnabled(false);
        jMenuItemKleinbuchstaben.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemKleinbuchstabenActionPerformed(evt);
            }
        });
        MenueBearbeiten.add(jMenuItemKleinbuchstaben);

        MenueBar.add(MenueBearbeiten);

        setJMenuBar(MenueBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jScrollPaneLinks, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118)
                .addComponent(jScrollPaneRechts, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonGrossbuchstaben, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonKleinbuchstaben, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jScrollPaneLinks, jScrollPaneRechts});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPaneRechts, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                    .addComponent(jScrollPaneLinks))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGrossbuchstaben, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonKleinbuchstaben, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jScrollPaneLinks, jScrollPaneRechts});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemBeendenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBeendenActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemBeendenActionPerformed

    private void jToolGrossbuchstabenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToolGrossbuchstabenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToolGrossbuchstabenActionPerformed

    private void jButtonGrossbuchstabenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGrossbuchstabenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonGrossbuchstabenActionPerformed

    private void jButtonKleinbuchstabenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKleinbuchstabenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonKleinbuchstabenActionPerformed

    private void jToolKleinbuchstabenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToolKleinbuchstabenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToolKleinbuchstabenActionPerformed

    private void jToolEinfuegenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToolEinfuegenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToolEinfuegenActionPerformed

    private void jToolAusschneidenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToolAusschneidenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToolAusschneidenActionPerformed

    private void jToolKopierenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToolKopierenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToolKopierenActionPerformed

    private void jMenuItemAusschneidenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAusschneidenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemAusschneidenActionPerformed

    private void jMenuItemKopierenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemKopierenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemKopierenActionPerformed

    private void jMenuItemEinfuegenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEinfuegenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemEinfuegenActionPerformed

    private void jMenuItemGrossbuchstabenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGrossbuchstabenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemGrossbuchstabenActionPerformed

    private void jMenuItemKleinbuchstabenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemKleinbuchstabenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemKleinbuchstabenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MenueBar;
    private javax.swing.JMenu MenueBearbeiten;
    private javax.swing.JMenu MenueDatei;
    private javax.swing.JTextArea TextAreaLinks;
    private javax.swing.JTextArea TextAreaRechts;
    private javax.swing.JToolBar ToolBar;
    private javax.swing.JButton jButtonGrossbuchstaben;
    private javax.swing.JButton jButtonKleinbuchstaben;
    private javax.swing.JMenuItem jMenuItemAusschneiden;
    private javax.swing.JMenuItem jMenuItemBeenden;
    private javax.swing.JMenuItem jMenuItemEinfuegen;
    private javax.swing.JMenuItem jMenuItemGrossbuchstaben;
    private javax.swing.JMenuItem jMenuItemKleinbuchstaben;
    private javax.swing.JMenuItem jMenuItemKopieren;
    private javax.swing.JScrollPane jScrollPaneLinks;
    private javax.swing.JScrollPane jScrollPaneRechts;
    private javax.swing.JPopupMenu.Separator jSeparatorBearbeiten;
    private javax.swing.JButton jToolAusschneiden;
    private javax.swing.JButton jToolEinfuegen;
    private javax.swing.JButton jToolGrossbuchstaben;
    private javax.swing.JButton jToolKleinbuchstaben;
    private javax.swing.JButton jToolKopieren;
    // End of variables declaration//GEN-END:variables


    
    
    
    DocumentListener documentListener = new DocumentListener() {
      public void changedUpdate(DocumentEvent documentEvent) {
        System.out.println("Changed Update");
      }
      public void insertUpdate(DocumentEvent documentEvent) {
        System.out.println("Insert Update");
        // Mind. ein Zeichen vorhanden --> Buttons aktivieren
      }
      public void removeUpdate(DocumentEvent documentEvent) {
        System.out.println("Remove Update");
        // Mind. ein Zeichen gelöscht - überprüfen ob leer - wenn nicht, dann Buttons aktiv. Wenn doch, dann Buttons deaktivieren.
      }
      
    };
    

public void DocumentListener (){
    TextAreaLinks.getDocument().addDocumentListener(documentListener);
    TextAreaRechts.getDocument().addDocumentListener(documentListener);
}






}
